Semana 1 - Modelagem
edirlucasi7/AluraTech pull request #1
Opened 2022-02-15 19:47 UTC by edirlucasi7

Realizando a modelagem inicial do projeto.

2022-02-16 23:02 UTC, edirlucasi7 commented
@thaisandre @mariasantosdev fiz as alterações solicitadas

2022-02-18 01:00 UTC, thaisandre requested changes

2022-02-18 01:00 UTC, thaisandre commented on alurinha/src/validators/EnumValidator.java
> +    }
**sugestões** (não precisa fazer):

**sugestão 1**: trocar nome do argumento `error` por `errorMessage` (essa sugestão vale para os demais validadores)

**sugestão 2**: achei curioso que você permite passar uma mensagem de erro que pode ser nula ou vazia. isso não é um problema, mas você poderia dar mais flexibilidade para quem vai chamar este método criando uma sobrecarga que não necessita da mensagem, exemplo:

``` java
public class EnumValidator {

    public static void cantBeNull(Enum field) {
        cantBeNull(field, "enum field should not be null");
    }

    public static void cantBeNull(Enum field, String errorMessage) {
        if(field == null) {
            throw new IllegalArgumentException(errorMessage);
        }
    }
}
```
dessa maneira, você não obriga quem vai chamar o método `cantBeNull()` de passar uma mensagem de erro com valor `null` caso não seja de interesse fazê-lo. (essa sugestão vale para os demais validadores)

**sugestão 3**: outra sugestão seria tentar criar um validador mais genérico e não um para cada tipo específico (`Enum`, `Integer`, `String`, etc...). por exemplo, para validar valores nulos:

```java
public class ValidatorUtils {

    public static void notNull(Object object) {
        notNull(object, "the object should not be null");
    }

    public static void notNull(Object object, String errorMessage) {
        if(object == null) {
            throw new IllegalArgumentException(errorMessage);
        }
    }
}
```

e daria para adicionar algumas outras validações aqui também e eliminar dos demais validadores que você fez. - fica de desafio ;)

2022-02-18 01:00 UTC, thaisandre commented on alurinha/src/validators/ObjectValidator.java
> +        }
as chamadas de `canBeNull()` dos demais validadores que você fez não precisariam existir e chamar este aqui, o que acha?

2022-02-18 01:00 UTC, thaisandre commented on alurinha/src/validators/StringValidator.java
> +        }
o que vai acontecer aqui se eu passar um `field` com valor `null`? (***request change**)

2022-02-18 01:00 UTC, thaisandre commented on alurinha/src/validators/StringValidator.java
> +    }
o mesmo aqui, o que acontece se eu passar um `field` com valor `null`? (***request change**)

2022-02-18 01:00 UTC, thaisandre commented on alurinha/src/validators/course/CourseValidator.java
> +}
você fez um validador específico para regra de negócio e isolou das validações genéricas, gosto dessa abordagem! muito bom! mas ela poderia ter ficado dentro da própria classe `Course`, o que acha? (***request change**)

2022-02-18 01:00 UTC, thaisandre commented on alurinha/src/com/br/levelup/model/Activity.java
> +    }
boa, validou e usou os setters!

2022-02-18 01:00 UTC, thaisandre commented on alurinha/src/com/br/levelup/model/utils/EstimateValuesUtils.java
> +    }
programação defensiva! muito bom!

sugestão: aqui eu apenas ajustaria a mensagem de erro para "The field value should not be less than zero!"  e mudaria o nome do método para  `cantBeLessOrEqualZero()` e encapsularia a validação dos valores que não podem ser nulo dentro do método `cantBeLessOrEqualZero()`, o que acha?


outra sugestão de melhoria:
```java
public static boolean minimumAndMaximumValue(Integer value, Integer minimum, Integer maximum) {
    cantBeLessOrEqualZeroOrNull(value, "The field value should not be less than zero or null!");
    cantBeLessOrEqualZeroOrNull(minimum, "The field minimum should not be less than zero or null!");
    cantBeLessOrEqualZeroOrNull(maximum, "The field maximum should not be less than zero or null!");
    return value.compareTo(minimum) >= 0 && value.compareTo(maximum) <= 0;
}
```

2022-02-18 01:00 UTC, thaisandre commented on alurinha/src/AluraTech.java
> +        System.out.println(category);
ótima bateria de testes, parabéns!

2022-02-18 01:08 UTC, thaisandre commented
parabéns, Edir! muito bom seu código! as sugestões que adicionei você fica livre para fazer ou não. 
apenas os comentários com ***request change** precisa arrumar

2022-02-18 13:56 UTC, edirlucasi7 commented on alurinha/src/validators/EnumValidator.java
> +    }
boa!

2022-02-18 14:00 UTC, edirlucasi7 commented on alurinha/src/validators/ObjectValidator.java
> +        }
muito bom :)

2022-02-18 14:47 UTC, mariasantosdev commented on alurinha/src/com/br/levelup/model/Instructor.java
> +public class Instructor {
Opa Edir aqui fiquei meio confusa...Você fez essa classe por conta do card de Course que diz: 
`- instrutor(a): nome do instrutor(a) que ministra o curso`, certo?
Mas na classe Course você colocou um atributo chamado instructorName....Teria que ser uma das duas abordagens(ou a classe Instructor com nome ou o atributo instructorName na classe Course)

2022-02-18 14:47 UTC, mariasantosdev commented on alurinha/src/com/br/levelup/model/Course.java
> +    private Integer estimatedTime;
minor do minor mas poderia colocar estimatedTimeInHours só para indicar que é em horas assim como você fez na classe Video com o `durationInMinutes` (bem opcional esse)

2022-02-18 14:47 UTC, mariasantosdev commented on alurinha/src/com/br/levelup/model/utils/EstimateValuesUtils.java
> +    }
Ótimos pontos @thaisandre

2022-02-18 14:47 UTC, mariasantosdev commented on alurinha/src/validators/StringValidator.java
> +    private static final Pattern CODECOLORHEXADECIMALFOTMAT = Pattern.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$");
CODECOLORHEXADECIMALFORMAT**
colocar um `R`no lugar do penultimo T

2022-02-18 14:47 UTC, mariasantosdev commented on alurinha/src/validators/StringValidator.java
> +    private static final Pattern CODECOLORHEXADECIMALFOTMAT = Pattern.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$");
minor - mas poderia separar cada palavra com `_` ficaria: CODE_FORMAT só para dar uma leitura melhor

2022-02-18 14:48 UTC, mariasantosdev commented on alurinha/src/com/br/levelup/model/Instructor.java
> +public class Instructor {
Se realmente for isso é o único que daria request change....

2022-02-18 15:07 UTC, edirlucasi7 commented on alurinha/src/validators/StringValidator.java
> +    private static final Pattern CODECOLORHEXADECIMALFOTMAT = Pattern.compile("^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$");
Obrigado madu :)

2022-02-19 10:43 UTC, thaisandre approved these changes

2022-02-19 10:43 UTC, thaisandre commented on alurinha/src/com/br/levelup/model/Explanation.java
> +        cantBeNull(section, "The object section should not be null!");
o objeto `section` já é validado na classe mãe `Activity` e você chamou o `super()` ali. então, não precisaria repetir ela aqui (***request change**)

2022-02-19 10:43 UTC, thaisandre commented on alurinha/src/com/br/levelup/model/Question.java
> +        cantBeNull(section, "The object section should not be null!");
mesma coisa aqui: o objeto `section` já é validado na classe mãe `Activity` e você chamou o `super()` ali. então, não precisaria repetir ela aqui (***request change**)

2022-02-19 10:43 UTC, thaisandre commented on alurinha/src/validators/course/CourseValidator.java
> +    private static final Integer STIMATEDTIMEMAX = 20;
trocar nome `STIMATEDTIMEMIN` por `ESTIMATEDTIMEMIN` (***request change**)
trocar nome `STIMATEDTIMEMAX`por `ESTIMATEDTIMEMAX` (***request change**)

2022-02-21 12:46 UTC, mariasantosdev approved these changes

2022-02-21 13:56 UTC, merged

2022-02-21 13:56 UTC, edirlucasi7 commented
PR fechado com #1