Semana 10
edirlucasi7/AluraTech pull request #10
Opened 2022-04-20 22:05 UTC by edirlucasi7

2022-04-25 12:46 UTC, thaisandre requested changes

2022-04-25 12:46 UTC, thaisandre commented on src/main/java/br/com/levelup/aluratech/config/security/SecurityConfigurations.java
> +                .anyRequest().authenticated()
da maneira que está funciona, mas é de costume deixarmos tudo que necessita de autenticação no início, ou seja, o que é mais restrito vem primeiro:

```
.antMatchers("/admin/**").authenticated()
.antMatchers("/api/categories/**").permitAll()
.antMatchers("/category/**").permitAll()
.antMatchers("/bGltcGEtby1jYWNoZS1kYS1hcGktYWU").permitAll()
.anyRequest().authenticated()
```

2022-04-25 12:46 UTC, thaisandre commented on pom.xml
> +		</dependency>
não estamos utilizando JWT, pode apagar esta dependência (***request changed**)

2022-04-25 12:46 UTC, thaisandre commented on src/main/java/br/com/levelup/aluratech/controller/request/UpdateSubCategoryRequest.java
> +        this.idCategory = subCategory.getCategory().getId();
poderia criar o método `getCategoryId()` dentro da classe `SubCategory` para evitar null pointer

2022-04-25 21:25 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/CourseController.java
> +        return "redirect:/admin/courses/"+possibleCourse.get().getCodeCategory()+"/"+possibleCourse.get().getCodeSubCategory();
você já recebe o code da category, subcategory e course na linha 109 poderia usar ele e evitar dar esse `get().get...()`

2022-04-25 21:25 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/api/CategoryApiController.java
> +    public String clearCacheApiCategories() {
[minor] - poderia colocar um `@ResponseStatus(HttpStatus.OK)` se quiser também Edir (tudo bem que você já deu a mensagem mas ainda acho legal retornar um 200 também)

2022-04-25 21:25 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/model/Course.java
> +    @NotNull(message = "A subcategoria deve ser obrigatório!")
"A subcategoria deve ser obrigatória!*

2022-04-25 21:25 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/model/User.java
> +    public Long getId() {
precisa desse getter? aqui mostra que não está sendo usado

2022-04-25 21:25 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/repository/CategoryRepository.java
> +    List<CategoriesWithSubCategoriesProjection> findCategoriesWithSubCategories();
poderia chamar `findActiveCategoriesWithSubCategories` oque acha? só para deixar claro que são somente as categorias ativas

2022-04-25 21:25 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/repository/CategoryRepository.java
> +    CategoryWithSubCategoriesAndCoursesProjection findCategoriesWithSubCategoryAndCourses(String categoryCode);
findActiveCategoriesWithSubCategoryAndCourses** oque acha? :eyes:

2022-04-25 21:25 UTC, mariasantosdev commented on src/main/resources/files/schema.sql
> +CREATE TABLE user_permissions (
essa tabela deveria ter uma PK ficaria mais ou menos assim 
`PRIMARY KEY (user_id, permissions_id)`

2022-04-25 21:25 UTC, mariasantosdev commented on src/main/resources/files/schema.sql
> +    password VARCHAR(255) NOT NULL
pra que essa coluna password aqui Edir??

2022-04-25 21:25 UTC, mariasantosdev commented on src/main/webapp/WEB-INF/views/category/publicPageCategory.jsp
> +        <title>Programação | Cursos online de tecnologia</title>
aqui no title o nome da categoria poderia ser dinamico também

2022-04-25 21:38 UTC, edirlucasi7 commented on src/main/java/br/com/levelup/aluratech/repository/CategoryRepository.java
> +    CategoryWithSubCategoriesAndCoursesProjection findCategoriesWithSubCategoryAndCourses(String categoryCode);
boa

2022-04-25 21:49 UTC, edirlucasi7 commented on src/main/resources/files/schema.sql
> +    password VARCHAR(255) NOT NULL
copiei e colei de user :( tirei ja

2022-04-25 22:06 UTC, edirlucasi7 commented on src/main/java/br/com/levelup/aluratech/controller/CourseController.java
> +        return "redirect:/admin/courses/"+possibleCourse.get().getCodeCategory()+"/"+possibleCourse.get().getCodeSubCategory();
Madu, nesse caso o fluxo muda, por exemplo, se eu estou em courses/programacao/java e no formulario eu atualizei para uma subcategoria kurbenetes que pertence a categoria devops, retornaria para programacao/java, sendo que eu queria que retornasse para courses/devops/kurbenetes.

2022-04-26 13:24 UTC, thaisandre approved these changes

2022-04-26 13:24 UTC, thaisandre commented on src/main/java/br/com/levelup/aluratech/controller/api/CategoryApiController.java
> +    public String clearCacheApiCategories() {
pode manter, mas não era necessário. como é um `RestController` o Spring já vai anotar este método com `@ResponseBody` que vai definir o status para 200

2022-04-26 17:06 UTC, mariasantosdev approved these changes

2022-04-26 17:07 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/CourseController.java
> +        return "redirect:/admin/courses/"+possibleCourse.get().getCodeCategory()+"/"+possibleCourse.get().getCodeSubCategory();
aah beleza @edirlucasi7!! faz sentidoo

2022-04-26 18:54 UTC, merged

2022-04-26 19:12 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/api/CategoryApiController.java
> +    public String clearCacheApiCategories() {
Verdade @thaisandre!! tem total razãoo! :heart: