Semana 4
edirlucasi7/AluraTech pull request #4
Opened 2022-03-09 22:51 UTC by edirlucasi7

2022-03-10 14:25 UTC, thaisandre requested changes

2022-03-10 14:25 UTC, thaisandre commented on src/main/java/com/br/levelup/AluraTechCsv.java
> +        try(PrintStream ps = new PrintStream("/home/icety/IdeaProjects/AluraTech/src/main/resources/script.sql")) {
cuidado! aqui você utilizou o caminho absoluto na sua máquina - não funciona na minha (***request changed**)

2022-03-10 14:25 UTC, thaisandre commented on src/test/java/com/br/levelup/SubCategoryTest.java
> +        Assertions.assertEquals(subCategories.subList(0, 2), subCategoriesWithDescription);
apenas sugestão (a mesma que comentei no `CategoryTest`). para ganhar semântica, você poderia fazer:

```java
assertTrue(subCategoriesWithDescription.size() == 2);
assertTrue(subCategoriesWithDescription.containsAll(List.of(subCategoryWithoutDescription1, subCategoryWithoutDescription2)));
assertFalse(subCategoriesWithDescription.contains(subCategoryWithDescription));
```

2022-03-10 14:25 UTC, thaisandre commented on src/test/java/com/br/levelup/CategoryTest.java
> +        Assertions.assertNotEquals(false, activeCategories.contains(inactiveCategory));
apenas sugestão. para ganhar semântica, você poderia fazer:

```java
assertTrue(activeCategories.size() == 2);
assertTrue(activeCategories.containsAll(List.of(activeCategory1, activeCategory2)));
assertTrue(activeCategories.contains(inactiveCategory));
```

2022-03-10 14:25 UTC, thaisandre commented on src/test/java/com/br/levelup/EstimateValuesUtilsTest.java
> +    }
bom teste, mas este é o melhor cenário! e se eu chamar este método como os exemplos abaixo, o que vai aocntecer? (***request changed**)

```java
minimumAndMaximumValue(estimatedTimeInHours, -1, 0);
minimumAndMaximumValue(estimatedTimeInHours, null, null);

2022-03-10 14:25 UTC, thaisandre commented on src/test/java/com/br/levelup/SubCategoryTest.java
> +        SubCategory inactiveSubCategory = new SubCategory("Business", "renda-variavel", category);
faltou o cenário em que a `subcategory` possui uma descrição nula (já que não é obrigatória!). o que vai acontecer? (***request changed**)

2022-03-10 14:25 UTC, thaisandre commented on src/test/java/com/br/levelup/SubCategoryTest.java
> +        SubCategory subCategoryWithDescription = new SubCategory("Business", "renda-variavel", category);
aqui também faltou o cenário em que a `subcategory` possui uma descrição nula (já que não é obrigatória!). o que vai acontecer? (*request changed)

2022-03-10 16:06 UTC, mariasantosdev requested changes

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/java/com/br/levelup/model/Category.java
> +        containOnlyLettersLowercaseAndDash(code, "The field code must not be out of lowercase letters and dash format!");
*containOnlyLettersLowerCaseAndDash minor do minor é só que lower é uma palavra e case outra então camelcase nelas :p

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/java/com/br/levelup/model/Course.java
> +        containOnlyLettersLowercaseAndNumbersAndDash(code);
containOnlyLettersLowerCaseAndNumbersAndDash**

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/java/com/br/levelup/service/CsvReaderService.java
> +    public static List<Category> csvReaderCategories(String file) throws IOException {
porque trocou o nome do método? ficou um pouco redundante.... pense em quando eu for chamar o método dessa classe: CsvReaderService.csvReaderCategories
O nome da classe já deixa claro que faz leitura de csv não precisa informar novamente isso no nome do método poderia ser somente CsvReaderService.readCategories, faz sentido?

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/resources/schema.sql
> +    order_in_category SMALLINT UNSIGNED,
não precisamos dizer que order_in_category essa é uma coluna que está dentro da tabela category, então fica claro que estamos falando sobre a ordem da categoria....
No card está escrito `a ordem em que aparecerá no sistema` dessa forma podemos entender que é a uma order_visualization, oque acha?

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/resources/schema.sql
> +    order_in_subcategory SMALLINT UNSIGNED,
mesmo comentário de cima

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/resources/schema.sql
> +    order_in_subcategory SMALLINT UNSIGNED,
bacana o UNSIGNED aqui!!

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/resources/schema.sql
> +    short_description LONGTEXT,
eu dei uma pesquisada melhor sobre o o LONGTEXT e me surpreendi pois ele guarda até 4.294.967.295 caracteres :o e isso é mais que demais hahha, vi que ele pode ser usado para armazenar até mesmo um livro inteiro :thinking: 

Nesse caso acho que poderiamos trocar para TEXT que é bemmm menor guardando 65,535 caracteres

https://dev.mysql.com/doc/refman/5.6/en/string-type-syntax.html

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/resources/schema.sql
> +    short_description LONGTEXT,
oque eu recomendo é: Tire todos os LONGTEXT eu usaria somente em um caso bem especifico que sei que pode ser muitooo grande, eu não vejo nenhuma coluna nessa e em nenhuma outra tabela que precise ser tão grande assim!! o TEXT vai atender na maioria dos casos e em alguns casos até o próprio VARCHAR atende muito bem!

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/resources/schema.sql
> +CREATE TABLE subcategory (
liberte essa tabela dos LONGTEXT hahaha

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/resources/schema.sql
> +      order_in_section TINYINT UNSIGNED,
order_visualization*

2022-03-10 16:06 UTC, mariasantosdev commented on src/main/resources/schema.sql
> +    type ENUM('SINGLE_ANSWER', 'MULTIPLE_ANSWERS', 'TRUE_OR_FALSE') DEFAULT 'SINGLE_ANSWER' NOT NULL,
Não será null pois por default ela é SINGLE_ANSWER, ou seja, não precisa do NOT NULL

2022-03-10 16:11 UTC, mariasantosdev commented on src/test/java/com/br/levelup/EstimateValuesUtilsTest.java
> +    }
ótimo ponto @thaisandre

2022-03-10 16:34 UTC, mariasantosdev commented
Acho legal seguir a organização dos packages, adicionar o package de model e de service aqui nos testes também

![image](https://user-images.githubusercontent.com/75762013/157709473-0b13f2b3-9373-4687-aa5b-b68a9239b92b.png)

2022-03-10 16:35 UTC, mariasantosdev requested changes

2022-03-10 16:35 UTC, mariasantosdev commented on src/test/java/com/br/levelup/SubCategoryTest.java
> +                () -> new Category(name, "java-a"));
você gostaria de testar o nome da SubCategory certo? estou o new é na SubCategory

2022-03-10 16:35 UTC, mariasantosdev commented on src/test/java/com/br/levelup/SubCategoryTest.java
> +                () -> new Category("Programacao", code));
Não seria para testar o code da SubCategory? poque se for da Category deveria estar no CategoryTest *request change

2022-03-10 16:35 UTC, mariasantosdev commented on src/test/java/com/br/levelup/SubCategoryTest.java
> +    void should_throw_exception_when_category_is_null(Category category) {
should_throw_exception_when_subcategory_is_null

2022-03-10 16:35 UTC, mariasantosdev commented on src/test/java/com/br/levelup/SubCategoryTest.java
> +        SubCategory inactiveSubCategory = new SubCategory("Business", "renda-variavel", category);
Ótimo ponto

2022-03-10 19:52 UTC, thaisandre approved these changes

2022-03-10 19:53 UTC, thaisandre commented
muito muito bom, novamente, Edir! parabéns! :)

2022-03-11 03:08 UTC, mariasantosdev commented
showw parabéns Edir, lets que bora codar a próxima semana :rocket:

2022-03-11 03:08 UTC, mariasantosdev approved these changes

2022-03-11 13:01 UTC, merged