Semana 5
edirlucasi7/AluraTech pull request #5
Opened 2022-03-16 18:37 UTC by edirlucasi7

2022-03-17 13:22 UTC, thaisandre requested changes

2022-03-17 13:22 UTC, thaisandre commented on src/main/java/com/br/levelup/AluraTechCsv.java
> +
quando eu rodei a primeira vez não escreveu essas linhas no *script* e deu erro pq o `instructor_id` não existia. como você fez uma classe para representar o instrutor e uma tabela à parte, seria interessante incluir no *script* os inserts necessários dos instrutores utilizados nos outros *inserts* para que tudo funcione corretamente (***request change**)

outra coisa, uma sugestão: nas linhas 29-31 você já leu os arquivos e já possui a lista de cada entidade. você poderia fazer com que os métodos `loadCategoryData()` `loadSubCategoryData()` e `loadCourseData()` receba cada uma destas listas como parâmetro ao invés do arquivo e ler novamente dentro de cada método (este aqui passou batido no último review, me desculpe - mas é apenas uma sugestão)

2022-03-17 13:22 UTC, thaisandre commented on src/main/java/com/br/levelup/InsertCourseWithJDBC.java
> +        Instructor instructor = new Instructor("Mario Souto");
aqui também deu erro já que o instrutor não existia. adicionar no script para conseguir rodar em qualquer máquina. (**request changed**)

2022-03-17 13:22 UTC, thaisandre commented on src/main/java/com/br/levelup/service/WriteSqlQueries.java
> +    }
pode excluir estes `throws IOException` de todos estes métodos e a implementação do primeiro método está com a identação errada (***request changed**)

2022-03-17 13:22 UTC, thaisandre commented on src/main/resources/script.sql
> +GROUP BY ca.name;
estes aqui deveriam ficar em um *script* separado já que este arquivo `script.sql` é o mesmo que você usa para escrever os outros via código e vai sobrescrever. (***request changed**)

2022-03-17 16:02 UTC, edirlucasi7 commented on src/main/java/com/br/levelup/AluraTechCsv.java
> +
sim sim, obrigado

2022-03-17 20:37 UTC, thaisandre approved these changes

2022-03-17 20:38 UTC, thaisandre commented
esta semana foram apenas detalhes e o PR ficou muito bom, Edir! parabéns!

2022-03-18 03:38 UTC, mariasantosdev approved these changes

2022-03-18 03:38 UTC, mariasantosdev commented on src/main/java/com/br/levelup/DAO/CourseDAO.java
> +                            rst.getInt(3), rst.getLong(4), rst.getString(5));
minor - Poderia passar o nome da coluna também só para facilitar a visualização. Nesse caso você passou o columnIndex mas no caso de adicionar o nome da coluna você passaria o columnLabel

2022-03-18 03:38 UTC, mariasantosdev commented on src/main/java/com/br/levelup/model/dto/CourseDTO.java
> +    private String subcategoryName;
Porque não serem final?

2022-03-18 03:38 UTC, mariasantosdev commented on src/main/java/com/br/levelup/model/dto/CourseDTO.java
> +    private String subcategoryName;
Eu prefiro separar esses dois atributos criando um SubCategoryDto para eles já que são campos que corresponde a subcategoria

2022-03-18 03:38 UTC, mariasantosdev commented on src/main/java/com/br/levelup/model/dto/CourseDTO.java
> +    private String subcategoryName;
Optional**

2022-03-18 03:40 UTC, mariasantosdev commented
Parabéns ta bem legal, coloquei somente alguns comentários mas todos opcionais :smile:

2022-03-18 13:40 UTC, merged