Semana 9
edirlucasi7/AluraTech pull request #9
Opened 2022-04-13 20:26 UTC by edirlucasi7

2022-04-13 21:35 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/AdminController.java
> +    public String redirectReport(Model model) {
Edir para que foi necessário receber o model aqui?

2022-04-13 21:35 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/CategoryController.java
> +    @PostMapping("/update/{idCategory}")
minor do minor mas poderia ser `disable-category/{idCategory}` porque quando eu li achei que era o meétodo que atualiza a categoria inteira e não somente a "visibilidade" dela

2022-04-13 21:35 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/SubCategoryController.java
> +        categories.forEach(c -> System.out.println(c.getId() + c.getName()));
sobrou esse System.out.println aquiii

2022-04-13 21:35 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/SubCategoryController.java
> +        Category possibleCategory = categoryRepository.findById(newSubCategoryRequest.getIdCategory()).get();
nesse caso não precisava se chamar `possibleCategory` mas sim `category` pensando que você deu um `.get()` no final e com isso parou de ser retornardo Opcional para ser retornado Category

2022-04-13 21:35 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/SubCategoryController.java
> +    @PostMapping("/admin/subcategories/update/{idSubCategory}")
o mesmo comentário do outro controller aqui!!

2022-04-13 21:35 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/projection/category/CategoryProjection.java
> +public interface CategoryProjection {
Não está mais sendo usado certo? Bora remover

2022-04-13 21:35 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/projection/report/ReportInstructorWithMoreCourses.java
> +public interface ReportInstructorWithMoreCourses {
poderia renomear para ReportInstructorWithMoreCoursesProjection, apenas para seguir o padrãozinho que você fez nos outros

2022-04-13 21:35 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/model/Course.java
> +
Aqui mostra que não está sendo usado esse método e nem o getSubCategory, não está mesmo ou meu intellij está doidãoo?

2022-04-13 21:35 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/model/Course.java
> +
Se não tiver bora deletar

2022-04-14 03:24 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/response/course/CourseResponse.java
> -    private final String developedSkills;
porque removeu o final aqui?

2022-04-14 03:24 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/controller/response/subcategory/SubCategoryResponse.java
> -    private final String studyGuide;
porque removeu o final?

2022-04-14 03:24 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/model/Category.java
> +        if(this.active == true) {
Como o this.active é um boolean  bastaria você colocar o
``` 
if(this.active) {
 this.active = false;
}
```

2022-04-14 03:24 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/model/SubCategory.java
> +        if(this.active == true) {
o mesmo comentário sobre simplificar essa condição

2022-04-14 03:24 UTC, mariasantosdev commented on src/main/java/br/com/levelup/aluratech/repository/InstructorRepository.java
> +    List<ReportInstructorWithMoreCourses> findInstructorWithMoreCourses();
Edir nem precisaria colocar o retorno como List, pois essa query nunca vai dar mais de um ReportInstructorWithMoreCourses já que demos um `LIMIT 1`, poderia até retonar um Optional pensando que pode existir ou não um instrutor com mais cursos, faz sentido?

2022-04-14 12:46 UTC, mariasantosdev commented on src/main/webapp/resources/js/category/disableCategory.js
> +        alert("Ocorreu um erro, tente novamente mais tarde!")
Hora você usa `;` hora não Edir, é importante manter o padrão, então ou remove de tudo ou coloca `;` em tudo

2022-04-14 12:46 UTC, mariasantosdev commented on src/main/webapp/resources/js/subcategory/disableSubCategory.js
> +    });
mesmo comentário sobre `;`

2022-04-14 13:06 UTC, thaisandre requested changes

2022-04-14 13:06 UTC, thaisandre commented on src/main/java/br/com/levelup/aluratech/controller/SubCategoryController.java
> +        Category possibleCategory = categoryRepository.findById(newSubCategoryRequest.getIdCategory()).get();
exato! e se não existir uma categoria com este id no banco? (***request changed**)

2022-04-14 13:06 UTC, thaisandre commented on src/main/java/br/com/levelup/aluratech/model/Course.java
> +
@mariasantosdev , está sendo usado na `listCourse.jsp`

2022-04-14 13:11 UTC, mariasantosdev commented
Ta bem bacana Edir :rocket:

2022-04-14 13:40 UTC, edirlucasi7 commented on src/main/java/br/com/levelup/aluratech/controller/response/course/CourseResponse.java
> -    private final String developedSkills;
estava com sobrecarga, dps que tirei pra fazer projection com interface esqueci de colocar de novo :(

2022-04-14 15:22 UTC, edirlucasi7 commented on src/main/java/br/com/levelup/aluratech/controller/SubCategoryController.java
> +        Category possibleCategory = categoryRepository.findById(newSubCategoryRequest.getIdCategory()).get();
Madu, eu acabei tirando a validação do id de categoria pq em NewCategoryRequest ja tem uma anotação @ExistsId e caso o id nao exista ja é retornado para o formulario :) falei com Thais

2022-04-14 15:31 UTC, thaisandre requested changes

2022-04-14 15:31 UTC, thaisandre commented on src/main/java/br/com/levelup/aluratech/controller/SubCategoryController.java
> +    @PostMapping("/admin/subcategories/disable-category/{idSubCategory}")
aqui deveria ser `/disable-subcategory` ao invés de `/disable-category`, não?

2022-04-14 15:32 UTC, thaisandre commented on src/main/java/br/com/levelup/aluratech/controller/SubCategoryController.java
> +    @PostMapping("/admin/subcategories/disable-category/{idSubCategory}")
e modificar lá no ajax do js também

2022-04-14 16:12 UTC, mariasantosdev approved these changes

2022-04-14 16:12 UTC, mariasantosdev commented on src/main/webapp/resources/js/category/disableCategory.js
> +        alert("Ocorreu um erro, tente novamente mais tarde!")
Só faltou o `;` aqui na 6

2022-04-14 16:12 UTC, mariasantosdev commented on src/main/webapp/resources/js/subcategory/disableSubCategory.js
> +        alert("Ocorreu um erro, tente novamente mais tarde!")
faltou aqui na 6 o `;`

2022-04-14 18:25 UTC, thaisandre approved these changes

2022-04-14 18:26 UTC, thaisandre commented
muito bom @edirlucasi7 ! parabéns

2022-04-14 20:52 UTC, merged